### ISSUE TITLE
Let's decide on a roadmap

### ISSUE THREAD

**Issue by victorb** [open-services/open-registry#22]
Here are my current idea for a roadmap. There is probably bunch of other things we want to tackle as well, please let me know if you think something is missing or something is there that is not important.

- [ ] Governance setup
  - [ ] Have at least other person in Leadership
  - [ ] Finish Contributing guidelines
  - [ ] Register non-profit / Join other non-profit 
- [ ] Infrastructure
  - [ ] At least one more person with access to infrastructure
  - [ ] Automatic deploys on change
  - [ ] Nightly runs for benchmarks and save daily reports
  - [ ] Setup metrics apis + dashboards
  - [ ] At least as fast as the npm registry in four key regions (Europe, North + South America and Asia)
- [ ] Financing setup
  - [ ] See historic expenses per day/month/year
  - [ ] See historic income per day/month/year
  - [ ] See current expected expenses
  - [ ] See current expected income
  - [ ] Website listing the above
  - [ ] Automate financing in a way that servers will continue running until funding runs out, without any required intervention from humans
- [ ] Specification for JavaScript Registry (include npm compat)
- [ ] Federation specification
- [ ] Test-Matrix of projects
  - [ ] Pick top 10 JS projects that works with npm + yarn + pnpm (react doesn't)
  - [ ] Ensure the same modules with the same structure is installed
  - [ ] Should run nightly together with benchmarks
  - [ ] Should be easy to run against local copy of the registry
- [ ] Publishing specification
  - [ ] Cryptographically signed packages
- [ ] Specification for migrating users from npm registry

**Comment by digitalextremist** [comment]
Pardon me, but what is the status of this project/initiative? I see a lot of great direction, but very few collaborators engaged. Has the group gone dormant, or are the items above still planned?

**Comment by digitalextremist** [comment]
Pardon me, but what is the status of this project/initiative? I see a lot of great direction, but very few collaborators engaged. Has the group gone dormant, or are the items above still planned?
